// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myivzyjkdhagxeccbukr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15aXZ6eWprZGhhZ3hlY2NidWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODkzMjEsImV4cCI6MjA3MzM2NTMyMX0.WmNcB1I5NrKA4TJWgVYjxXsn85bMsFRd5BBD-xbNxZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});